### ISSUE TITLE
Outreachy Contributions (chinmaychahar)

### ISSUE THREAD

**Issue by chinmaychahar** [bokeh/outreach-programs#15]
As @bryevdv mentioned [here](https://github.com/bokeh/outreach-programs/issues/6#issuecomment-1465501145),

I'm opening this issue to discuss my contributions to Bokeh docs and open issues, my progress and receive feedbacks from time to time. 

I've worked on all the micro tasks mentioned and my day-to-day progress to the project is being captured in this gist - https://gist.github.com/chinmaychahar/0ed22cff050d4329007ef9c679198857 

I'd particularly like to discuss my work on Data Visualization with the NYC Taxi Trip dataset. I'm continously working on analysis and visualization in the notebook mentioned below and would love to interact, discuss and receive feedbacks from the mentors. 

Notebook - https://gist.github.com/chinmaychahar/0ed22cff050d4329007ef9c679198857#my-implementation-can-be-found-here-colab-notebook

cc @pavithraes @bryevdv

**Comment by bryevdv** [comment]
Thanks for the very detailed work log @chinmaychahar! we are working to catch up on detailed feedback but I did want to quickly acknowledge that the micro-tasks have been satisfied!

**Comment by pavithraes** [comment]
Thanks for the comprehensive notes you've taken along the way, it makes reviewing very pleasant. :)

Just to note, xref: #13 is the corresponding PR.

**Comment by chinmaychahar** [comment]
Hi @pavithraes, I appreciate the feedback! 
I had a small query. While recording our contributions on the outreachy website, should we only include merged PRs or open issues and PRs as well? Thanks

**Comment by pavithraes** [comment]
@chinmaychahar You can include all issues and PRs, they don't necessarily need to have been resolved. :)

**Comment by pavithraes** [comment]
@chinmaychahar Your notebook exploring the NYC taxi dataset looks great!

Some quick thoughts to help improve your submission:

- Add a list of requirements (`requiremets.txt` or `environment.yml`) to allow folks to quickly run/reproduce your notebook. For example, I think you may have used bokeh-2.4.3 to create these visuals? So some things may not work as expected with the latest bokeh-3.03. This is alright, we just need to know which version you used. :)
- Thanks for including the column metadata information in your notebook — very helpful!
- I like the narrative bits to explain why we’re doing certain operations. You can consider more of these text elements, especially for the second half of your notebooks. If you’d like to go a step further, you can create different sections/headings to add more flow.
- For “Scatter Plot b/w start and end location”, you need to move `colors = np.array([(r, g, 150) for r, g in zip(50+2*x, 30+2*y)], *dtype*="uint8")` after the x and y assignments.
- 3rd plot onwards would benefit from axis labels, to quickly understand what’s being presented.
- Looking at your imports, were you intending to create rows/columns/tabs? If not, you can consider removing those to keep the notebook minimal. 

These are just suggestions, so please feel free to make changes as you see fit. :)

**Comment by pavithraes** [comment]
Also, I think we can track your contributions in this issue to keep all discussions in one place. If you agree, please go ahead and close the PR #13.

**Comment by chinmaychahar** [comment]
Thanks for the detailed feedback,
I will surely keep your suggestions in mind and incorporate them going forward as I add more visualizations to the notebook. 

**Edit:** Made all the suggested changes! Will be updating more visualizations soon @pavithraes

**Comment by chinmaychahar** [comment]
Hello @pavithraes 
I've worked some more on the notebook keeping in mind the pointers you mentioned and added more visualizations. Please review and revert back with any suggestions/tips/feedbacks you might have :D

**Comment by chinmaychahar** [comment]
I'd also like to discuss the project timeline for my final application so it would be great if you're up for discussing that anytime soon @pavithraes 
Cheers!
