### ISSUE TITLE
Bokeh#1_discription_withLinks(AS)

### ISSUE THREAD

**Issue by anushka-png** [bokeh/outreach-programs#19]
# Fundamentals of Data Visualization in Bokeh

I have tried to work with two different datasets first one is TLC Driver 24 hour course and second one is yellow taxi dataset for the month oct and nov . Also for the reference  , have attached a pdf containing my outputs and other relevant data as well .I am contributing to a project for the first time .I appreciate any reviews and comment on it

## New York City Taxi TLC Driver Education Course Price Dataset

This dataset contains a list of authorized providers who offer the TLC Driver License 24 hour TLC Driver Education Course and exam. All TLC Driver License applicants must complete the course, which covers the following topics: TLC rules and regulations, geography, safe driving skills, traffic rules, and customer service. The dataset includes details about each driving school, such as their contact information, locations, languages offered, and the course price for each.

## New York City Taxi Yellow Taxi Oct-Nov Dataset

This dataset contains information about yellow taxis in New York City between the months of October and November. It includes data on the number of passengers, total and fare amount, tips, extra charges, vendor ID, and more.

You can find the code and visualizations(pdf) for both datasets in this [Google Drive folder](https://drive.google.com/drive/folders/1Z-NZPpH-6mJxMYF0G-LXyf7eF6AR95ow?usp=sharing).

github gist link : https://gist.github.com/anushka-png/ffd9d83d2b6b46d169c5e510dc4123d9

**Comment by pavithraes** [comment]
@anushka-png Thanks for sharing! This satisfies the microtask, and we'll share more detailed feedback soon. :)

**Comment by anushka-png** [comment]
Sure mam , thank you

**Comment by anushka-png** [comment]
@pavithraes  @bryevdv ,is there anything else to cover if not may you please approve this so that I can submit my final application as this is my main project which I wanted to focus on and would like to have a final review for internship.

I had a great learning experience here ,interacting with lots of students and tried Bokeh for the first time and gave my best of my ability  and really loved this tool. Hoping to work on it further if provided this wonderful opportunity, not only I can get a good grab on data visualization tool but since I am targeting  to get a ML engineer or data scientist  role it can really make me prepared for the future analysis as well.

Thank you for your time and guidance .Looking for a positive response from your side .

Thanks a lot again

**Comment by bryevdv** [comment]
@anushka-png thanks for the kind words, FYI @pavithraes already approved this above!

**Comment by anushka-png** [comment]
Got it , Thank you
