### ISSUE TITLE
Ajoke Outreachy Contributions 

### ISSUE THREAD

**Issue by Ajoke23** [bokeh/outreach-programs#24]
The link : https://docs.bokeh.org/en/dev-3.1/docs/dev_guide to the most recent developer documentation (note that the version selector says 3.1.0rc1) to set up your development environment is broken

**Comment by pavithraes** [comment]
Thank you for surfacing this! Bokeh-3.1.0 is now released, so the latest docs are accurate.

I've updated the task description, closing as resolved!
