### ISSUE TITLE
Setting up my environment

### ISSUE THREAD

**Issue by Ajoke23** [bokeh/outreach-programs#32]
@bryevdv @pavithraes Please kindly review. This was setup since last week. I await your feedbacks
![bokehversion](https://user-images.githubusercontent.com/71567200/226183817-f0e81f30-8c58-4354-8683-6c0d0e951388.PNG)
![githubplot](https://user-images.githubusercontent.com/71567200/226183850-6fe9e4b5-75f4-4cb4-825b-a737c8533d9c.PNG)

**Comment by bryevdv** [comment]
@Ajoke23 looks like you are all set up 👍 (micro-task is satisfied)

**Comment by Ajoke23** [comment]
Thanks for the feedback. Since it's satisfied, can it be closed
