### ISSUE TITLE
Wrong path mentioned in a command for running bokeh server

### ISSUE THREAD

**Issue by Med16-11** [bokeh/outreach-programs#9]
Hello @pavithraes !
While setting up the environment, I have noticed that in the command mentioned in the documentation is not providing right file path.
It should be 
BOKEH_DEV=false python -m bokeh serve --show examples/server/app/sliders.py 
instead of 
BOKEH_DEV=false python -m bokeh serve --show examples/app/sliders.py

![Screenshot from 2023-03-09 00-57-30](https://user-images.githubusercontent.com/78318301/223823779-907d3e66-6514-4c1a-b1b0-d62981421cd4.png)

**Comment by Oluwatobioguntolu** [comment]
Thank you!

**Comment by whoisorioki** [comment]
I encountered the same problem!

**Comment by chinmaychahar** [comment]
I think a relevant PR has been created for this issue and it should be updated with the next release. See [#12910](https://github.com/bokeh/bokeh/pull/12910)

**Comment by bryevdv** [comment]
Yes this fix was merged and will appear when the version 3.2 docs are published (which may be a month or two away). Thanks for the issue!
